{
 "title": "Mina benchmarks",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "gitbranchFilterQuery",
    "label": "Git branch",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"mina-benchmarks\",\n  tag: \"gitbranch\"\n)"
   },
   {
    "name": "fieldFilterQuery",
    "label": "Category",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"mina-benchmarks\",\n  tag: \"_field\"\n)"
   },
   {
    "name": "measurementFilterQuery",
    "label": "Measurement",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"mina-benchmarks\",\n  tag: \"_measurement\"\n)"
   }
  ]
 },
 "panels": [
  { "title": "General (all branches)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mina base",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^mina-base$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^${gitbranchFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Ledger export",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^ledger-export$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^${gitbranchFilterQuery:regex}$/)\n  //|> group(columns: [\"_field\", \"gitbranch\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Proofs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^snark$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^${gitbranchFilterQuery:regex}$/)\n  |> group(columns: [\"_field\", \"gitbranch\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "zkApps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^zkapp$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^${gitbranchFilterQuery:regex}$/)\n  |> group(columns: [\"_field\", \"gitbranch\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Heap usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^heap_usage$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\")\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^${gitbranchFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\", \"gitbranch\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Mina base (compatible ⇄ develop)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ledger_hash.merge (compatible)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^mina-base$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^compatible$/)\n  |> filter(fn: (r) => r._measurement =~ /Ledger_hash\\.merge.*/ )\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Ledger_hash.merge (develop)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^mina-base$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^develop$/)\n  |> filter(fn: (r) => r._measurement =~ /Ledger_hash\\.merge.*/ )\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Vrf eval checked (compatible)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^mina-base$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^compatible$/)\n  |> filter(fn: (r) => r._measurement =~ /^vrf eval checked$/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Vrf eval checked (develop)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^mina-base$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^develop$/)\n  |> filter(fn: (r) => r._measurement =~ /^vrf eval checked$/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Vrf eval  unchecked (compatible)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^mina-base$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^compatible$/)\n  |> filter(fn: (r) => r._measurement =~ /^vrf eval unchecked$/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Vrf eval  unchecked (develop)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^mina-base$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^develop$/)\n  |> filter(fn: (r) => r._measurement =~ /^vrf eval unchecked$/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Ledger export (compatible ⇄ develop)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Convert accounts for config (compatible)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^ledger-export$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^compatible$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^convert_accounts_for_config$/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Convert accounts for config (develop)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^ledger-export$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^develop$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^convert_accounts_for_config$/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Parse runtime config (compatible)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^ledger-export$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^compatible$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^parse_runtime_config$/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Parse runtime config (develop)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^ledger-export$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^develop$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^parse_runtime_config$/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Serialize runtime config (compatible)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^ledger-export$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^compatible$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^serialize_runtime_config$/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Serialize runtime config (develop)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^ledger-export$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^develop$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^serialize_runtime_config$/)\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Snark (compatible ⇄ develop)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proofs (compatible)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^snark$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^compatible$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  //|> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Proofs (develop)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^snark$/)\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${fieldFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^develop$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  //|> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    }
   ]
  },
  {
   "title": "ZkApp (compatible ⇄ develop)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total account updates (compatible)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^zkapp$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"total account updates\")\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^compatible$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Total account updates (develop)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^zkapp$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"total account updates\")\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^develop$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Proofs updates (compatible)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^zkapp$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"proofs updates\")\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^compatible$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Proofs updates (develop)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^zkapp$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"proofs updates\")\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^develop$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Pairs of signed (compatible)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^zkapp$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"pairs of signed\")\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^compatible$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Pairs of signed (develop)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^zkapp$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"pairs of signed\")\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^develop$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Signed updates (compatible)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^zkapp$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"signed updates\")\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^compatible$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Signed updates (develop)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^zkapp$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"signed updates\")\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^develop$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Cost (compatible)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^zkapp$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"cost\")\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^compatible$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Cost (develop)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^zkapp$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"cost\")\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^develop$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Heap usage (compatible ⇄ develop)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes (compatible)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^heap_usage$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\")\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^compatible$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Bytes (develop)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^heap_usage$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\")\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^develop$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Words (compatible)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^heap_usage$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"heap words\")\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^compatible$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Words (develop)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"mina-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"category\"] =~ /^heap_usage$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"heap words\")\n  |> filter(fn: (r) => r[\"gitbranch\"] =~ /^develop$/)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${measurementFilterQuery:regex}$/)\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
      }
     ]
    }
   ]
  }
 ]
}