{
 "title": "o1js benchmarks",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "benchmarkFilterQuery",
    "label": "Benchmark",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"o1js-benchmarks\",\n  tag: \"benchmarkName\",\n  start: v.timeRangeStart\n)"
   },
   {
    "name": "sourceEnvironmentFilterQuery",
    "label": "Source environment",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"o1js-benchmarks\",\n  tag: \"sourceEnvironment\",\n  start: v.timeRangeStart\n)"
   },
   {
    "name": "operatingSystemFilterQuery",
    "label": "OS",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"o1js-benchmarks\",\n  tag: \"operatingSystem\",\n  start: v.timeRangeStart\n)"
   },
   {
    "name": "hardwareFilterQuery",
    "label": "Hardware",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"o1js-benchmarks\",\n  tag: \"hardware\",\n  start: v.timeRangeStart\n)"
   },
   {
    "name": "gitBranchFilterQuery",
    "label": "Git branch",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"o1js-benchmarks\",\n  tag: \"gitBranch\",\n  start: v.timeRangeStart\n)"
   },
   {
    "name": "sampledTimesFilterQuery",
    "label": "Sampled times",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"o1js-benchmarks\",\n  tag: \"sampledTimes\",\n  start: v.timeRangeStart\n)"
   }
  ]
 },
 "panels": [
  { "title": "Initialization benchmarks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "o1labs_zkapp_for_e2e_testing_compilation",
     "query": "from(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^init - o1js import - \\d+ samples$/ or r[\"_measurement\"] =~ /^init - bindings initialization - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] =~ /^${sourceEnvironmentFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitBranch\"] =~ /^${gitBranchFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "elapsedTime" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "sourceEnvironment", "operator": "=~", "value": "/^$query0$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$query1$/" },
      { "condition": "AND", "key": "os", "operator": "=~", "value": "/^$query2$/" },
      { "condition": "AND", "key": "hardware", "operator": "=~", "value": "/^$query3$/" },
      { "condition": "AND", "key": "runtime", "operator": "=~", "value": "/^$query4$/" }
     ]
    }
   ]
  },
  {
   "title": "GitHub Actions against the 'main' branch with confidence interval",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "o1labs_zkapp_for_e2e_testing_compilation",
     "query": "from(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^init - o1js import - \\d+ samples$/ or r[\"_measurement\"] =~ /^init - bindings initialization - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n  |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n\nfrom(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^init - o1js import - \\d+ samples$/ or r[\"_measurement\"] =~ /^init - bindings initialization - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"o1js import - upperBound\")\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n  |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> yield(name: \"o1jsImportUpperBoundMax\")\n\nfrom(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^init - o1js import - \\d+ samples$/ or r[\"_measurement\"] =~ /^init - bindings initialization - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"o1js import - lowerBound\")\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n  |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n  |> yield(name: \"o1jsImportLowerBoundMin\")\n\nfrom(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^init - o1js import - \\d+ samples$/ or r[\"_measurement\"] =~ /^init - bindings initialization - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"bindings initialization - upperBound\")\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n  |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> yield(name: \"bindingsInitUpperBoundMax\")\n\nfrom(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^init - o1js import - \\d+ samples$/ or r[\"_measurement\"] =~ /^init - bindings initialization - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"bindings initialization - lowerBound\")\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n  |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n  |> yield(name: \"bindingsInitLowerBoundMin\")",
     "select": [
      [
       { "params": [ "elapsedTime" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "sourceEnvironment", "operator": "=~", "value": "/^$query0$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$query1$/" },
      { "condition": "AND", "key": "os", "operator": "=~", "value": "/^$query2$/" },
      { "condition": "AND", "key": "hardware", "operator": "=~", "value": "/^$query3$/" },
      { "condition": "AND", "key": "runtime", "operator": "=~", "value": "/^$query4$/" }
     ]
    }
   ]
  },
  {
   "title": "Min by 'mean'",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^init - o1js import - \\d+ samples$/ or r[\"_measurement\"] =~ /^init - bindings initialization - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] =~ /^${sourceEnvironmentFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitBranch\"] =~ /^${gitBranchFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> group()\n  |> min()\n  |> yield(name: \"min\")"
    }
   ]
  },
  {
   "title": "Max by 'mean'",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^init - o1js import - \\d+ samples$/ or r[\"_measurement\"] =~ /^init - bindings initialization - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] =~ /^${sourceEnvironmentFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitBranch\"] =~ /^${gitBranchFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> group()\n  |> max()\n  |> yield(name: \"max\")"
    }
   ]
  },
  { "title": "ECDSA benchmarks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "All",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "o1labs_zkapp_for_e2e_testing_compilation",
     "query": "from(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^ecdsa - build constraint system - \\d+ samples$/ or r[\"_measurement\"] =~ /^ecdsa - witness generation - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] =~ /^${sourceEnvironmentFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitBranch\"] =~ /^${gitBranchFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^ecdsa - build constraint system - \\d+ samples$/ or r[\"_measurement\"] =~ /^ecdsa - witness generation - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"build constraint system - upperBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] =~ /^${sourceEnvironmentFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"gitBranch\"] =~ /^${gitBranchFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n//   |> yield(name: \"buildConstraintSystemUpperBoundMax\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^ecdsa - build constraint system - \\d+ samples$/ or r[\"_measurement\"] =~ /^ecdsa - witness generation - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"build constraint system - lowerBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] =~ /^${sourceEnvironmentFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"gitBranch\"] =~ /^${gitBranchFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n//   |> yield(name: \"buildConstraintSystemLowerBoundMin\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^ecdsa - build constraint system - \\d+ samples$/ or r[\"_measurement\"] =~ /^ecdsa - witness generation - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"witness generation - upperBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] =~ /^${sourceEnvironmentFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"gitBranch\"] =~ /^${gitBranchFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n//   |> yield(name: \"witnessGenerationUpperBoundMax\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^ecdsa - build constraint system - \\d+ samples$/ or r[\"_measurement\"] =~ /^ecdsa - witness generation - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"witness generation - lowerBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] =~ /^${sourceEnvironmentFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"gitBranch\"] =~ /^${gitBranchFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n//   |> yield(name: \"witnessGenerationLowerBoundMin\")",
     "select": [
      [
       { "params": [ "elapsedTime" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "sourceEnvironment", "operator": "=~", "value": "/^$query0$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$query1$/" },
      { "condition": "AND", "key": "os", "operator": "=~", "value": "/^$query2$/" },
      { "condition": "AND", "key": "hardware", "operator": "=~", "value": "/^$query3$/" },
      { "condition": "AND", "key": "runtime", "operator": "=~", "value": "/^$query4$/" }
     ]
    }
   ]
  },
  {
   "title": "GitHub Actions against the 'main' branch with confidence interval",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "o1labs_zkapp_for_e2e_testing_compilation",
     "query": "from(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^ecdsa - build constraint system - \\d+ samples$/ or r[\"_measurement\"] =~ /^ecdsa - witness generation - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n  |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n\nfrom(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^ecdsa - build constraint system - \\d+ samples$/ or r[\"_measurement\"] =~ /^ecdsa - witness generation - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"build constraint system - upperBound\")\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n  |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> yield(name: \"buildConstraintSystemUpperBoundMax\")\n\nfrom(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^ecdsa - build constraint system - \\d+ samples$/ or r[\"_measurement\"] =~ /^ecdsa - witness generation - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"build constraint system - lowerBound\")\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n  |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n  |> yield(name: \"buildConstraintSystemLowerBoundMin\")\n\nfrom(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^ecdsa - build constraint system - \\d+ samples$/ or r[\"_measurement\"] =~ /^ecdsa - witness generation - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"witness generation - upperBound\")\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n  |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> yield(name: \"witnessGenerationUpperBoundMax\")\n\nfrom(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^ecdsa - build constraint system - \\d+ samples$/ or r[\"_measurement\"] =~ /^ecdsa - witness generation - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"witness generation - lowerBound\")\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n  |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n  |> yield(name: \"witnessGenerationLowerBoundMin\")",
     "select": [
      [
       { "params": [ "elapsedTime" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "sourceEnvironment", "operator": "=~", "value": "/^$query0$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$query1$/" },
      { "condition": "AND", "key": "os", "operator": "=~", "value": "/^$query2$/" },
      { "condition": "AND", "key": "hardware", "operator": "=~", "value": "/^$query3$/" },
      { "condition": "AND", "key": "runtime", "operator": "=~", "value": "/^$query4$/" }
     ]
    }
   ]
  },
  {
   "title": "Min by 'mean'",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^ecdsa - build constraint system - \\d+ samples$/ or r[\"_measurement\"] =~ /^ecdsa - witness generation - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] =~ /^${sourceEnvironmentFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitBranch\"] =~ /^${gitBranchFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> group()\n  |> min()\n  |> yield(name: \"min\")"
    }
   ]
  },
  {
   "title": "Max by 'mean'",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^ecdsa - build constraint system - \\d+ samples$/ or r[\"_measurement\"] =~ /^ecdsa - witness generation - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] =~ /^${sourceEnvironmentFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitBranch\"] =~ /^${gitBranchFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> group()\n  |> max()\n  |> yield(name: \"max\")"
    }
   ]
  },
  { "title": "Transaction benchmarks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "All",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "o1labs_zkapp_for_e2e_testing_compilation",
     "query": "from(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] =~ /^${sourceEnvironmentFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitBranch\"] =~ /^${gitBranchFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "elapsedTime" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "sourceEnvironment", "operator": "=~", "value": "/^$query0$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$query1$/" },
      { "condition": "AND", "key": "os", "operator": "=~", "value": "/^$query2$/" },
      { "condition": "AND", "key": "hardware", "operator": "=~", "value": "/^$query3$/" },
      { "condition": "AND", "key": "runtime", "operator": "=~", "value": "/^$query4$/" }
     ]
    }
   ]
  },
  {
   "title": "GitHub Actions against the 'main' branch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "o1labs_zkapp_for_e2e_testing_compilation",
     "query": "from(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n  |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"simple zkapp deploy transaction construction - upperBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n//   |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n//   |> yield(name: \"simpleZkappDeployTransactionConstructionUpperBoundMax\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"simple zkapp deploy transaction construction - lowerBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n//   |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n//   |> yield(name: \"simpleZkappDeployTransactionConstructionLowerBoundMin\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"simple zkapp deploy transaction signing - upperBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n//   |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n//   |> yield(name: \"simpleZkappDeployTransactionSigningUpperBoundMax\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"simple zkapp deploy transaction signing - lowerBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n//   |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n//   |> yield(name: \"simpleZkappDeployTransactionSigningLowerBoundMin\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"simple zkapp deploy transaction local sending - upperBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n//   |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n//   |> yield(name: \"simpleZkappDeployTransactionLocalSendingUpperBoundMax\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"simple zkapp deploy transaction local sending - lowerBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n//   |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n//   |> yield(name: \"simpleZkappDeployTransactionLocalSendingLowerBoundMin\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"simple zkapp call transaction construction - upperBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n//   |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n//   |> yield(name: \"simpleZkappCallTransactionConstructionUpperBoundMax\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"simple zkapp call transaction construction - lowerBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n//   |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n//   |> yield(name: \"simpleZkappCallTransactionConstructionLowerBoundMin\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"simple zkapp call transaction signing - upperBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n//   |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n//   |> yield(name: \"simpleZkappCallTransactionSigningUpperBoundMax\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"simple zkapp call transaction signing - lowerBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n//   |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n//   |> yield(name: \"simpleZkappCallTransactionSigningLowerBoundMin\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"simple zkapp call transaction local sending - upperBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n//   |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n//   |> yield(name: \"simpleZkappCallTransactionLocalSendingUpperBoundMax\")\n\n// from(bucket: \"o1js-benchmarks\")\n//   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n//   |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n//   |> filter(fn: (r) => r[\"_field\"] == \"simple zkapp call transaction local sending - lowerBound\")\n//   |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sourceEnvironment\"] == \"o1js GitHub Actions\")\n//   |> filter(fn: (r) => r[\"gitBranch\"] == \"main\")\n//   |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n//   |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n//   |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n//   |> yield(name: \"simpleZkappCallTransactionLocalSendingLowerBoundMin\")\n",
     "select": [
      [
       { "params": [ "elapsedTime" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "sourceEnvironment", "operator": "=~", "value": "/^$query0$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$query1$/" },
      { "condition": "AND", "key": "os", "operator": "=~", "value": "/^$query2$/" },
      { "condition": "AND", "key": "hardware", "operator": "=~", "value": "/^$query3$/" },
      { "condition": "AND", "key": "runtime", "operator": "=~", "value": "/^$query4$/" }
     ]
    }
   ]
  },
  {
   "title": "Min by 'mean'",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] =~ /^${sourceEnvironmentFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitBranch\"] =~ /^${gitBranchFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> group()\n  |> min()\n  |> yield(name: \"min\")"
    }
   ]
  },
  {
   "title": "Max by 'mean'",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"o1js-benchmarks\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp deploy transaction local sending - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction construction - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction signing - \\d+ samples$/ or r[\"_measurement\"] =~ /^txn - simple zkapp call transaction local sending - \\d+ samples$/)\n  |> filter(fn: (r) => r[\"benchmarkName\"] =~ /^${benchmarkFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sourceEnvironment\"] =~ /^${sourceEnvironmentFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"operatingSystem\"] =~ /^${operatingSystemFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"hardware\"] =~ /^${hardwareFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"gitBranch\"] =~ /^${gitBranchFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"sampledTimes\"] =~ /^${sampledTimesFilterQuery:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> group()\n  |> max()\n  |> yield(name: \"max\")"
    }
   ]
  }
 ]
}